title: Work Hard
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
timezone:    Asia/Shanghai
future:      true
highlighter: rouge
markdown:    GFM
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed
